### ISSUE TITLE
Change the title

### ISSUE THREAD

**Issue by fbkarsdorp** [fbkarsdorp/tune-twins#65]
I don't think we should do this, as we _are_ effectively learning a similarity metric, and
the system can give a similarity value for arbitrary melodies (whether that similarity
value is any good, and thus, whether our system generalized beyond the folk tune data set
is of course to be seen).

**Comment by emanjavacas** [comment]
The generalization issues are quite general to perhaps the whole field of ML rather than to the similarity learning approach, so I don't see why that'd invalidate the claims we are making. Also the approach is easily extensible to other melody representation methods. A point that the reviewer is trying to make (that learning a similarity is unfeasible given only class labels) kind of goes against the entire framework of similarity learning. All in all, not enough to motivate a title change.
